### ISSUE TITLE
Neighborhood sample exception

### ISSUE THREAD

**Issue by hectcastro** [azavea/modellab-geoprocessing#42]
```
[WARN] [12/08/2015 18:08:57.755] [ForkJoinPool-4-worker-7] [ActorSystem(spray-system)] Request to http://modellab.azavea.com/sample/JFSBHRQ/12/-75.13343811035156/40.00868343656941?bufferSize=2 could not be handled normally
        at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)
        at scala.collection.Iterator$$anon$2.next(Iterator.scala:37)
        at scala.collection.IndexedSeqLike$Elements.next(IndexedSeqLike.scala:64)
        at scala.collection.IterableLike$class.head(IterableLike.scala:91)
        at scala.collection.mutable.ArrayBuffer.scala$collection$IndexedSeqOptimized$$super$head(ArrayBuffer.scala:47)
        at scala.collection.IndexedSeqOptimized$class.head(IndexedSeqOptimized.scala:120)
        at scala.collection.mutable.ArrayBuffer.head(ArrayBuffer.scala:47)
        at com.azavea.modellab.SampleNeighborhood.stitch(SampleNeighborhood.scala:23)
        at com.azavea.modellab.SampleNeighborhood$$anonfun$sample$1.apply(SampleNeighborhood.scala:55)
        at com.azavea.modellab.SampleNeighborhood$$anonfun$sample$1.apply(SampleNeighborhood.scala:53)
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
        at scala.util.Try$.apply(Try.scala:161)
        at scala.util.Success.map(Try.scala:206)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
java.util.NoSuchElementException: next on empty iterator
```

**Comment by echeipesh** [comment]
Looks like it tried to stitch tiles for area where there are no tiles at all. Guessing the worms eye view indicator was dragged outside the area of interest? If so a silly failure I should have thought of.
